INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (1,'Arise','Arose','Arisen','Surgir / Levantarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (2,'Awake','Awoke','Awoken','Despertarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (3,'Be','Was/Were','Been','Ser/Estar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (4,'Bear','Bore','Borne/Born','Soportar / Dar a luz');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (5,'Beat','Beat','Beaten','Golpear');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (6,'Become','Became','Become','Llegar a Ser');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (7,'Begin','Began','Begun','Empezar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (8,'Bend','Bent','Bent','Doblar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (9,'Bet','Bet','Bet','Apostar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (10,'Bind','Bound','Bound','Atar / Encuadernar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (11,'Bid','Bid','Bid','Pujar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (12,'Bite','Bit','Bitten','Morder');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (13,'Bleed','Bled','Bled','Sangrar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (14,'Blow','Blew','Blown','Soplar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (15,'Break','Broke','Broken','Romper');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (16,'Breed','Bred','Bred','Criar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (17,'Bring','Brought','Brought','Traer / Llevar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (18,'Broadcast','Broadcast','Broadcast','Radiar / Emitir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (19,'Build','Built','Built','Edificar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (20,'Burn','Burnt/Burned','Burnt/Burned','Quemar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (21,'Burst','Burst','Burst','Reventar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (22,'Buy','Bought','Bought','Comprar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (23,'Cast','Cast','Cast','Arrojar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (24,'Catch','Caught','Caught','Coger');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (25,'Come','Came','Come','Venir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (26,'Cost','Cost','Cost','Costar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (27,'Cut','Cut','Cut','Cortar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (28,'Choose','Chose','Chosen','Elegir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (29,'Cling','Clung','Clung','Agarrarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (30,'Creep','Crept','Crept','Arrastrarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (31,'Deal','Dealt','Dealt','Tratar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (32,'Dig','Dug','Dug','Cavar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (33,'Do (Does)','Did','Done','Hacer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (34,'Draw','Drew','Drawn','Dibujar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (35,'Dream','Dreamt/Dreamed','Dreamt/Dreamed','Soñar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (36,'Drink','Drank','Drunk','Beber');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (37,'Drive','Drove','Driven','Conducir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (38,'Eat','Ate','Eaten','Comer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (39,'Fall','Fell','Fallen','Caer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (40,'Feed','Fed','Fed','Alimentar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (41,'Feel','Felt','Felt','Sentir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (42,'Fight','Fought','Fought','Luchar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (43,'Find','Found','Found','Encontrar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (44,'Flee','Fled','Fled','Huir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (45,'Fly','Flew','Flown','Volar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (46,'Forbid','Forbade','Forbidden','Prohibir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (47,'Forget','Forgot','Forgotten','Olvidar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (48,'Forgive','Forgave','Forgiven','Perdonar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (49,'Freeze','Froze','Frozen','Helar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (50,'Get','Got','Got/Gotten','Obtener');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (51,'Give','Gave','Given','Dar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (52,'Go (Goes)','Went','Gone','Ir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (53,'Grow','Grew','Grown','Crecer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (54,'Grind','Ground','Ground','Moler');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (55,'Hang','Hung','Hung','Colgar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (56,'Have','Had','Had','Haber o Tener');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (57,'Hear','Heard','Heard','Oir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (58,'Hide','Hid','Hidden','Ocultar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (59,'Hit','Hit','Hit','Golpear');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (60,'Hold','Held','Held','Agarrar / Celebrar / Mantener');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (61,'Hurt','Hurt','Hurt','Herir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (62,'Keep','Kept','Kept','Conservar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (63,'Know','Knew','Known','Saber Conocer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (64,'Kneel','Knelt','Knelt','Arrodillarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (65,'Knit','Knit','Knit','Hacer punto');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (66,'Lay','Laid','Laid','Poner');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (67,'Lead','Led','Led','Conducir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (68,'Lean','Leant','Leant','Apoyarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (69,'Leap','Leapt','Leapt','Brincar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (70,'Learn','Learnt/Learned','Learnt/Learned','Aprender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (71,'Leave','Left','Left','Dejar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (72,'Lend','Lent','Lent','Prestar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (73,'Let','Let','Let','Permitir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (74,'Lie','Lay','Lain','Echarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (75,'Light','Lit','Lit','Encender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (76,'Lose','Lost','Lost','Perder');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (77,'Make','Made','Made','Hacer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (78,'Mean','Meant','Meant','Significar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (79,'Meet','Met','Met','Reunirse / Conocer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (80,'Mistake','Mistook','Mistaken','Equivocar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (81,'Overcome','Overcame','Overcome','Vencer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (82,'Pay','Paid','Paid','Pagar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (83,'Put','Put','Put','Poner');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (84,'Read','Read','Read','Leer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (85,'Ride','Rode','Ridden','Montar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (86,'Ring','Rang','Rung','Llamar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (87,'Rise','Rose','Risen','Levantarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (88,'Run','Ran','Run','Correr');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (89,'Say','Said','Said','Decir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (90,'See','Saw','Seen','Ver');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (91,'Seek','Sought','Sought','Buscar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (92,'Sell','Sold','Sold','Vender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (93,'Send','Sent','Sent','Enviar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (94,'Set','Set','Set','Poner(se)');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (95,'Sew','Sewed','Sewed/Sewn','Coser');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (96,'Shake','Shook','Shaken','Sacudir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (97,'Shear','Shore','Shorn','Esquilar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (98,'Shine','Shone','Shone','Brillar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (99,'Shoot','Shot','Shot','Disparar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (100,'Show','Showed','Shown','Mostrar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (101,'Shrink','Shrank','Shrunk','Encogerse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (102,'Shut','Shut','Shut','Cerrar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (103,'Sing','Sang','Sung','Cantar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (104,'Sink','Sank','Sunk','Hundir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (105,'Sit','Sat','Sat','Sentarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (106,'Sleep','Slept','Slept','Dormir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (107,'Slide','Slid','Slid','Resbalar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (108,'Smell','Smelt','Smelt','Oler');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (109,'Sow','Sowed','Sowed/Sown','Sembrar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (110,'Speak','Spoke','Spoken','Hablar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (111,'Speed','Sped','Sped','Acelerar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (112,'Spell','Spelt','Spelt','Deletrear');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (113,'Spend','Spent','Spent','Gastar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (114,'Spill','Spilt/Spilled','Spilt/Spilled','Derramar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (115,'Spin','Spun','Spun','Hilar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (116,'Spit','Spat','Spat','Escupir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (117,'Split','Split','Split','Rajar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (118,'Spoil','Spoilt/Spoiled','Spoilt/Spoiled','Estropear');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (119,'Spread','Spread','Spread','Extender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (120,'Spring','Sprang','Sprung','Saltar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (121,'Stand','Stood','Stood','Estar en pie');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (122,'Steal','Stole','Stolen','Robar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (123,'Stick','Stuck','Stuck','Pegar Engomar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (124,'Sting','Stung','Stung','Picar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (125,'Stink','Stank/Stunk','Stunk','Apestar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (126,'Stride','Strode','Stridden','Dar zancadas');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (127,'Strike','Struck','Struck','Golpear / Atacar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (128,'Swear','Swore','Sworn','Jurar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (129,'Sweat','Sweat','Sweat','Sudar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (130,'Sweep','Swept','Swept','Barrer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (131,'Swell','Swelled','Swollen','Hinchar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (132,'Swim','Swam','Swum','Nadar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (133,'Swing','Swung','Swung','Columpiarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (134,'Take','Took','Taken','Coger');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (135,'Teach','Taught','Taught','Enseñar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (136,'Tear','Tore','Torn','Rasgar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (137,'Tell','Told','Told','Decir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (138,'Think','Thought','Thought','Pensar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (139,'Throw','Threw','Thrown','Arrojar / Tirar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (140,'Thrust','Thrust','Thrust','Introducir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (141,'Tread','Trod','Trodden','Pisar, hollar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (142,'Understand','Understood','Understood','Entender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (143,'Undergo','Underwent','Undergone','Sufrir');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (144,'Undertake','Undertook','Undertaken','Emprender');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (145,'Wake','Woke','Woken','Despertarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (146,'Wear','Wore','Worn','Llevar puesto');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (147,'Weave','Wove','Woven','Tejer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (148,'Weep','Wept','Wept','Llorar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (149,'Wet','Wet','Wet','Mojar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (150,'Win','Won','Won','Ganar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (151,'Wind','Wound','Wound','Enrollar');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (152,'Withdraw','Withdrew','Withdrawn','Retirarse');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (153,'Wring','Wrung','Wrung','Torcer');
INSERT INTO verbos (id,infinitive,past_simple,past_participle,spanish) VALUES (154,'Write','Wrote','Written','Escribir');
